# Generated by Django 3.0.6 on 2020-07-30 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('age', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('entered', models.DateTimeField()),
                ('type', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'animal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('thumbnail', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Animal')),
            ],
            options={
                'db_table': 'photo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('info', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Animal')),
            ],
            options={
                'db_table': 'application',
                'managed': True,
            },
        ),
    ]
