# Generated by Django 3.0.6 on 2020-07-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
