# Generated by Django 3.0.6 on 2020-08-05 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200730_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Animal'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Animal'),
        ),
    ]
