# Generated by Django 3.0.6 on 2020-08-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200806_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
