# Generated by Django 3.0.8 on 2020-08-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200807_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
